//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIA
    {
        public string MaLoaiXe { get; set; }
        public System.DateTime Ngay { get; set; }
        public Nullable<decimal> GiaXe { get; set; }
        public Nullable<decimal> LuuDem { get; set; }
        public Nullable<decimal> NgoaiGio { get; set; }
        public string MoTa { get; set; }
    }
}
