//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public int MaHD { get; set; }
        public Nullable<int> MaYC { get; set; }
        public Nullable<int> TongTien { get; set; }
        public string TrangThai { get; set; }
        public string HangXe { get; set; }
        public string NoiDung { get; set; }
    
        public virtual YEUCAU YEUCAU { get; set; }
    }
}
