//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONTT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADONTT()
        {
            this.XE_HDTT = new HashSet<XE_HDTT>();
        }
    
        public string SoHDTT { get; set; }
        public string SoHD { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string HinhThucTT { get; set; }
        public Nullable<int> TongXeThue { get; set; }
        public Nullable<decimal> TraTruoc { get; set; }
        public Nullable<decimal> PhiPS { get; set; }
        public string LyDo { get; set; }
        public Nullable<decimal> TongThanhToan { get; set; }
        public Nullable<decimal> SoTienNop { get; set; }
        public string TenLaiXe { get; set; }
        public string TenKeToan { get; set; }
    
        public virtual HOPDONG HOPDONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XE_HDTT> XE_HDTT { get; set; }
    }
}
