//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHUCHI
    {
        public int MaPhieu { get; set; }
        public string LoaiPhieu { get; set; }
        public Nullable<int> SoTien { get; set; }
        public string NVXuLy { get; set; }
        public Nullable<System.DateTime> NgayTT { get; set; }
        public string PhuongThucTT { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> MaKhach { get; set; }
        public Nullable<int> MaXe { get; set; }
    
        public virtual KHACH KHACH { get; set; }
        public virtual XE XE { get; set; }
    }
}
