//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDatabaseFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rentaldbEntities : DbContext
    {
        public rentaldbEntities()
            : base("name=rentaldbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETHOPDONG> CHITIETHOPDONGs { get; set; }
        public virtual DbSet<DATXE> DATXEs { get; set; }
        public virtual DbSet<HOADONTT> HOADONTTs { get; set; }
        public virtual DbSet<HOPDONG> HOPDONGs { get; set; }
        public virtual DbSet<KHACH> KHACHes { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<SOXE> SOXEs { get; set; }
        public virtual DbSet<SUACHUA> SUACHUAs { get; set; }
        public virtual DbSet<XE> XEs { get; set; }
        public virtual DbSet<XE_HDTT> XE_HDTT { get; set; }
    }
}
