//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOXE
    {
        public string SoHD { get; set; }
        public int MaXe { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<decimal> TienThue { get; set; }
    
        public virtual HOPDONG HOPDONG { get; set; }
        public virtual XE XE { get; set; }
    }
}
