//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUACHUA
    {
        public System.DateTime NgaySua { get; set; }
        public int MaXe { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<System.DateTime> NgaySuaXong { get; set; }
        public string GhịChu { get; set; }
        public Nullable<decimal> TienChiPhi { get; set; }
    
        public virtual XE XE { get; set; }
    }
}
