//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class XE_HDTT
    {
        public string SoHDTT { get; set; }
        public int MaXe { get; set; }
        public Nullable<System.DateTime> NgayNhanXe { get; set; }
        public Nullable<System.DateTime> NgayTraXe { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual HOADONTT HOADONTT { get; set; }
        public virtual XE XE { get; set; }
    }
}
