//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class XERA
    {
        public System.DateTime NgayRa { get; set; }
        public int MaXe { get; set; }
        public System.TimeSpan GioRa { get; set; }
        public string GhiChu { get; set; }
    
        public virtual XE XE { get; set; }
    }
}
