//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class YEUCAU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YEUCAU()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public int MaYC { get; set; }
        public int MaKhach { get; set; }
        public int MaXe { get; set; }
        public Nullable<System.DateTime> NgayLay { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayTaoYC { get; set; }
        public string NVXuLy { get; set; }
        public Nullable<System.DateTime> ThoiGianXuLy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual KHACH KHACH { get; set; }
        public virtual XE XE { get; set; }
    }
}
